- name: add apt key for wsdd (make samba shares visible on Windows)
  apt_key:
    url: https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key
    state: present

- name: Add repository to install wsdd
  apt_repository:
    repo: deb https://pkg.ltec.ch/public/ focal main
    state: present

- name: install samba and nfs file server applications
  package:
    name: [samba,nfs-kernel-server,nfs-common,cifs-utils,wsdd]
    state: latest
