---

- hosts: all
  become: true
  roles:
    - basic_pkgs

- hosts: all
  become: true
  roles:
    - user_config

- hosts: all
  become: true
  roles:
    - zsh
      
- hosts: file_servers
  become: true
  roles:
    - file_server

- hosts: serverpi
  become: true
  vars_files:
    - secrets.yaml
  roles:
    - serverpi

- hosts: apache
  become: true
  roles:
    - apache

- hosts: webdav
  become: true
  vars_files:
    - secrets.yaml
  roles:
    - webdav

- hosts: another_lu
  become: true
  roles:
    - another_lu

- hosts: nginx
  become: true
  roles:
    - nginx

- hosts: reverse_proxy
  become: true
  roles:
    - reverse_proxy

- hosts: ddclient, ddclient_fallback
  become: true
  roles:
    - ddclient_setup

- hosts: ddclient
  become: true
  roles:
    - ddclient

- hosts: ddclient_fallback
  become: true
  roles:
    - ddclient_fallback

- hosts: mariaDB
  become: true
  roles:
    - mariaDB

- hosts: PHP
  become: true
  roles:
    - PHP

- hosts: redis
  become: true
  roles:
    - redis

- hosts: nextcloud
  become: true
  vars_files:
    - secrets.yaml
  roles:
    - nextcloud
    - nextcloud_post_install

- hosts: pihole
  become: true
  vars_files:
    - secrets.yaml
  roles:
    - pihole
    - pihole_post_install
