---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository cache
    tags: always
    package:
      update_cache: yes

- hosts: all
  become: true
  tasks:
 
  - name: install the basic packages
    tags: always
    package:
      name: [htop,neofetch,tree,zsh,ranger,unzip,git,vim-nox,speedtest-cli,wget,curl,tmux,rsync,locate,numlockx]
      state: present 

- hosts: all
  become: true
  tasks:

  - name: copy tmux configuration file
    copy:
      src: .tmux.conf
      dest: /home/eddie/
      owner: eddie
      mode: 0664

- hosts: all
  remote_user: eddie
  become_user: eddie
  roles:
    - ansible-ohmyzsh

- hosts: file_servers
  become: true
  tasks:

    - name: install samba and nfs file server applications
      package:
        name: [samba,nfs-kernel-server,nfs-common]
        state: latest
