---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository cache
    tags: always
    package:
      update_cache: yes

- hosts: all
  become: true
  tasks:
 
  - name: install the basic packages
    tags: always
    package:
      name: [htop,neofetch,tree,zsh,ranger,unzip,git,vim-nox,speedtest-cli,wget,curl,tmux,rsync,locate,numlockx]
      state: present 

