---

- hosts: all
  become: true
  pre_tasks:

  - name: update the repository cache
    package:
      update_cache: yes

  - name: create ansible user
    user:
      name: ansible
      groups: root

