---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository cache
    tags: always
    package:
      update_cache: yes

- hosts: all
  become: true
  tasks:
 
  - name: install the basic packages
    tags: always
    package:
      name: [htop,neofetch,tree,zsh,ranger,unzip,git,vim-nox,speedtest-cli,wget,curl,tmux,rsync,locate,numlockx]
      state: present 

- hosts: all
  become: true
  tasks:

  - name: copy tmux configuration file
    copy:
      src: .tmux.conf
      dest: /home/eddie/
      owner: eddie
      mode: 0664

- hosts: all
  roles:
    - ansible-ohmyzsh

- hosts: all
  tasks:

  - name: clone zsh auto-suggestion repo
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

  - name: clone zsh syntax highlighting repo
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

  - name: clone zsh typewritten theme
    git:
      repo: https://github.com/reobin/typewritten.git
      dest: ~/.oh-my-zsh/custom/themes/typewritten

- hosts: file_servers
  become: true
  tasks:

    - name: install samba and nfs file server applications
      package:
        name: [samba,nfs-kernel-server,nfs-common]
        state: latest
