---

- hosts: all
  become: true
  pre_tasks:

  - name: update the repository cache
    package:
      update_cache: yes

  - name: create ansible user
    user:
      name: ansible
      groups: root

# This allows to connect to the clients without the need of the sudo password    
  - name: copy sudoer_ansible file to /etc/sudoers.d/ansible
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440
