---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository cache
    tags: always
    package:
      update_cache: yes
      cache_valid_time: 18000

- hosts: all
  become: true
  tasks:
 
  - name: install the basic packages
    tags: always
    package:
      name: [htop,neofetch,tree,zsh,ranger,unzip,git,vim-nox,speedtest-cli,wget,curl,tmux,rsync,locate,numlockx]
      state: present 

- hosts: all
  become: true
  tasks:

  - name: copy tmux configuration file
    copy:
      src: .tmux.conf
      dest: /home/eddie/
      owner: eddie
      mode: 0664

- hosts: all
  roles:
    - ansible-ohmyzsh

- hosts: all
  tasks:

  - name: clone zsh auto-suggestion repo
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

  - name: clone zsh syntax highlighting repo
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

  - name: clone zsh typewritten theme
    git:
      repo: https://github.com/reobin/typewritten.git
      dest: ~/.oh-my-zsh/custom/themes/typewritten

- hosts: serverpi
  become: true
  tasks:

  - name: create folders for file sharing
    file:
      path: '/mnt/{{ item }}'
      state: directory
      mode: '0777'
      owner: nobody
      group: nogroup
    loop:
      - Backup
      - Music
      - Photos

- hosts: file_servers
  become: true
  tasks:

  - name: install samba and nfs file server applications
    package:
      name: [samba,nfs-kernel-server,nfs-common,cifs-utils]
      state: latest


- hosts: serverpi
  become: true
  tasks:

  - name: add samba shares to smb.conf
    blockinfile:
      dest: /etc/samba/smb.conf
      block: "{{ lookup('file', 'serverpi_samba') }}"
      insertafter: "EOF"
      backup: yes

  - name: Create samba users
    shell: "(echo {{ item.smbpass }}; echo {{ item.smbpass }}) | smbpasswd -s -a {{ item.user }}"
    loop:
      - { user: 'eddie', smbpass: 'serverpi' }
    register: smbuser

  - name: restart samba service
    service: 
      name: smbd
      state: restarted

  - name: add nfs exports to /etc/exports
    blockinfile:
      dest: /etc/exports
      block: "{{ lookup('file', 'serverpi_nfs') }}"
      insertafter: "EOF"
      backup: yes
    register: nfs_export

  - name: restart nfs service
    service:
      name: nfs-kernel-server
      state: restarted
    when: nfs_export.changed

- hosts: [serverpi,192.168.1.140]
  become: true
  tasks:

  - name: install apache webserver
    apt:
      name: [apache2-utils,apache2]
      state: latest

  - name: enable dav and dav_fs apache modules
    community.general.apache2_module:
      name: "{{ item }}"
      state: present
    loop:
      - dav_fs
      - dav
