---

- hosts: all
  become: true
  pre_tasks:

  - name: update the repository cache
    tags: always
    package:
      update_cache: yes
      cache_valid_time: 18000

  - name: upgrade packages
    tags: always
    apt:
      upgrade: dist

  - name: set timezone to Australia/Melbourne
    tags: always
    timezone:
      name: Australia/Melbourne
    register: timezone

  - name: restart crond after timezone changes
    tags: always
    service:
      name: cron
      state: restarted
    when: timezone.changed

############################################################################
# Creates user eddie to clients and give him admin privileges and prompt
# to change password if necessary and uploads user ssh key
  - name: create eddie user
    tags: firstrun
    user:
      name: eddie
      password: '$1$zxzUnL3B$LGqg.T838RZWrTxjQ5ORf.'
      update_password: on_create
      create_home: yes
      groups: users,sudo
      append: yes
    register: user_eddie

  - name: make /bin/bash the default shell on creation
    tags: firstrun
    user:
      name: eddie
      shell: /bin/bash
    when: user_eddie.changed

  - name: copy sudoer_eddie file to /etc/sudoers.d/eddie
    copy:
      src: sudoer_eddie
      dest: /etc/sudoers.d/eddie
      owner: root
      group: root
      mode: 0440
    when: user_eddie.changed

  - name: copy SSH key eddie user
    authorized_key:
      user: eddie
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHwLqywqLhqZ5Nj03X6LYppdAUofFDCv8mNS+cOns/E7 eddie main key      

#############################################################################
# This allows to connect to the clients without the need of the sudo password    
  - name: create ansible user
    tags: firstrun
    user:
      name: ansible
      groups: root
      shell: /bin/bash

  - name: copy sudoer_ansible file to /etc/sudoers.d/ansible
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: copy the SSH key ansible user
    authorized_key:
      user: ansible
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOWBKMr4lAZEzKiqXslcqDgmId5MCgQw3Pf2tNRWeNee ansible key

############################################################################

- hosts: clients
  become: true
  tasks:

  - name: reboot clients
    tags: never 
    reboot:
