---

- hosts: all
  become: true
  pre_tasks:
  roles:
    - first_setup

- hosts: [singleuser,multiuser]
  become: true
  roles:
    - users

- hosts: clients
  become: true
  tasks:

  - name: reboot clients
    tags: never 
    reboot:
