---

- hosts: all
  become: true
  pre_tasks:

  - name: update the repository cache
    tags: always
    package:
      update_cache: yes

  - name: create ansible user
    tags: always
    user:
      name: ansible
      groups: root

#############################################################################
# This allows to connect to the clients without the need of the sudo password    
  - name: copy sudoer_ansible file to /etc/sudoers.d/ansible
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: copy the SSH key ansible user
    authorized_key:
      user: ansible
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOWBKMr4lAZEzKiqXslcqDgmId5MCgQw3Pf2tNRWeNee ansible key

############################################################################

  - name: upgrade packages
    tags: always
    apt:
      upgrade: dist

- hosts: clients
  become: true
  tasks:

  - name: reboot clients
    tags: never 
    reboot:
