---

- hosts: all
  become: true
  pre_tasks:

  - name: update the repository cache
    tags: always
    package:
      update_cache: yes
      cache_valid_time: 18000

  - name: upgrade packages
    tags: always
    apt:
      upgrade: dist

  - name: set timezone to Australia/Melbourne
    tags: always
    timezone:
      name: Australia/Melbourne
    register: timezone

  - name: restart crond after timezone changes
    tags: always
    service:
      name: cron
      state: restarted
    when: timezone.changed

#############################################################################
# This allows to connect to the clients without the need of the sudo password    
  - name: create ansible user
    tags: always
    user:
      name: ansible
      groups: root
      shell: /bin/bash

  - name: copy sudoer_ansible file to /etc/sudoers.d/ansible
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: copy the SSH key ansible user
    authorized_key:
      user: ansible
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOWBKMr4lAZEzKiqXslcqDgmId5MCgQw3Pf2tNRWeNee ansible key

############################################################################

- hosts: clients
  become: true
  tasks:

  - name: reboot clients
    tags: never 
    reboot:
