---

- name: Check if .zshrc exists
  tags: zsh
  stat:
    path: /home/ansible/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  tags: zsh
  stat:
    path: /home/ansible/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning  oh-my-zsh
  tags: zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/ansible/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Creating new ~/.zshrc
  tags: zsh
  copy:
    src: /home/ansible/.oh-my-zsh/templates/zshrc.zsh-template
    dest: /home/ansible/.zshrc
    remote_src: yes
  when: not stat_rc_result.stat.exists

- name: clone zsh auto-suggestion repo
  tags: zsh
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /home/ansible/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: clone zsh syntax highlighting repo
  tags: zsh
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/ansible/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: clone zsh typewritten theme
  tags: zsh
  git:
    repo: https://github.com/reobin/typewritten.git
    dest: /home/ansible/.oh-my-zsh/custom/themes/typewritten

- name: remove comment from enable correction field
  tags: zsh
  lineinfile:
    path: /home/ansible/.zshrc
    regexp: '^# ENABLE_CORRECTION="true"'
    line: 'ENABLE_CORRECTION="true"'

- name: enable oh-my-zsh plugins
  tags: zsh
  lineinfile:
    path: /home/ansible/.zshrc
    regexp: '^plugins='
    line: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting)'

- name: comment original theme
  tags: zsh
  lineinfile:
    path: /home/ansible/.zshrc
    regexp: '^ZSH_THEME="robby'
    line: '#ZSH_THEME="robbyrussel"'

- name: insert reobin/typenwritten theme
  tags: zsh
  blockinfile:
    path: /home/ansible/.zshrc
    marker: "## {mark} TypenWritten theme ##"
    block: |
      ZSH_THEME="typewritten/typewritten"
      TYPEWRITTEN_PROMPT_LAYOUT="multiline"
      TYPEWRITTEN_SYMBOL="->"
      TYPEWRITTEN_RELATIVE_PATH="adaptive"
      TYPEWRITTEN_CURSOR="block"
    insertafter: '^#ZSH_THEME="robby'

- name: insert some aliases
  tags: zsh
  blockinfile:
    path: /home/ansible/.zshrc
    marker: "## {mark} Aliases ##"
    block: |
      alias l='ls -CF'
      alias la='ls -A'
      alias ll='ls -alhF'
      alias ls='ls --color=auto'
    insertafter: "^# alias"    

- name: insert aliases for apt
  tags: zsh
  blockinfile:
    path: /home/ansible/.zshrc
    marker: "## {mark} Apt aliases ##"
    block: |
      alias aptu='sudo apt update; sudo apt upgrade -y; sudo apt autopurge -y'
      alias apti='sudo apt update; sudo apt install'
      alias aptd='sudo apt update; sudo apt autoremove -y'
      alias apts='sudo apt search'
    insertafter: "^## END Aliases"
  when: ansible_distribution in ["Ubuntu","Debian"]

- name: insert aliases for apk
  tags: zsh
  blockinfile:
    path: /home/ansible/.zshrc
    marker: "## {mark} Apk aliases ##"
    block: |
      alias apku='sudo apk -U upgrade'
      alias apki='sudo apt add'
      alias apkd='sudo apk del'
      alias apks='sudo apk search'
    insertafter: "^## END Aliases"
  when: ansible_distribution == "Alpine"

- name: insert aliases for dnf 
  tags: zsh
  blockinfile:
    path: /home/ansible/.zshrc
    marker: "## {mark} Dnf aliases ##"
    block: |
      alias dnfu='sudo dnf upgrade -y'
      alias dnfi='sudo dnf install'
      alias dnfdd='sudo dnf remove'
      alias dnfs='sudo dnf search'
    insertafter: "^## END Aliases"
  when: ansible_distribution in ["Rocky"]

- name: insert alias for python3
  tags: zsh
  lineinfile:
    path: /home/ansible/.zshrc
    line: "alias python3='python3.10'"
    insertafter: EOF
  when: ansible_distribution in ["Rocky"]

- name: copy the .oh-my-zsh to users
  tags: zsh
  copy:
    remote_src: yes
    src: /home/ansible/.oh-my-zsh
    dest: "/home/{{ item.name }}/"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  loop: "{{ users }}"

- name: copy the .zshrc file to users
  tags: zsh
  copy:
    remote_src: yes
    src: /home/ansible/.zshrc
    dest: "/home/{{ item.name }}/"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0644
  loop: "{{ users }}"

- name: make zsh the default shell for users
  shell:
    cmd: "sed -i '/{{ item.name }}/s/[^\/]*sh$/zsh/' /etc/passwd"
  loop: "{{ users }}"
