- name: update repository cache
  tags: always
  package:
    update_cache: yes
    cache_valid_time: 18000

- name: upgrade packages
  tags: always
  apt:
    upgrade: dist

- name: install the basic packages
  tags: always
  package:
    name: [htop,neofetch,tree,zsh,ranger,unzip,git,vim-nox,speedtest-cli,python3-passlib,wget,curl,tmux,rsync,locate,numlockx]
    state: latest
