- name: Proxmox pre-update steps
  block:

    - name: disable pve-enterprise repository (Proxmox)
      tags: always
      lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: 'pve-enterprise$'
        line: '#deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise'

    - name: enable no-subscription repository (Proxmox)
      tags: always
      lineinfile: 
        path: /etc/apt/sources.list
        line: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        create: yes

    - name: remove proxmox subscription message
      tags: always
      replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        before: 'No valid subscription'
        regexp: '[^/]Ext.Msg.show'
        replace: 'void({ //Ext.Msg.show'

  when: ansible_cmdline['root'] == "/dev/mapper/pve-root"

- name: upgrade (Ubuntu/Debian)
  tags: always
  apt:
    update_cache: yes
    cache_valid_time: 18000
    upgrade: dist
  when: ansible_distribution in ["Ubuntu", "Debian"]
  register: upgrade

- name: upgrade (Alpine)
  tags: always
  apk:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Alpine"

- name: pre upgrade steps (Rocky Linux)
  tags: always
  block:

    - name: install Epel repository
      dnf:
        name: epel-release
        state: latest
      register: epel

    - name: enable PowerTools repository
      shell:
        cmd: "dnf config-manager --set-enabled powertools"
      when: epel.changed

    - name: install Remi repository
      dnf:
        name: "http://rpms.remirepo.net/enterprise/remi-release-8.rpm"
        state: latest
        disable_gpg_check: yes
      register: remi

    - name: enable php 8.0
      shell:
        cmd: "dnf module enable php:remi-8.0 -y"
      when: remi.changed

    - name: upgrade (Rocky)
      dnf:
        name: "*"
        state: latest

  when: ansible_distribution == "Rocky"

- name: install the basic packages
  tags: always
  package:
    name: [htop,neofetch,tree,zsh,ranger,unzip,git,"{{ vim }}",speedtest-cli,wget,curl,tmux,rsync,"{{ locate }}","{{ numlockx }}"]
    state: latest

- name: install more basic packages for Alpine
  tags: always
  apk:
    name: [lsof,less,lsblk,util-linux]
    state: latest
  when: ansible_distribution == "Alpine"

- name: add a cron job for updatedb (locate) every 10min
  tags: always
  cron:
    name: "Update database for locate"
    minute: "*/5"
    job: "updatedb"

- name: install dark mode for Proxmox
  tags: always
  shell:
    cmd: bash <(curl -s https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.sh ) install
    executable: /bin/bash
  when: 
    - ansible_cmdline['root'] == "/dev/mapper/pve-root"
    - upgrade.changed
