- name: upgrade (Ubuntu/Debian)
  tags: always
  apt:
    update_cache: yes
    cache_valid_time: 18000
    upgrade: dist
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: prepare and upgrade Alpine Linux
  block:

    - name: enable edge repositories
      tags: always
      shell:
        cmd: sed -i '2s/^http/#http/' /etc/apk/repositories; sed -i '4,5s/#http/http/' /etc/apk/repositories
    
    - name: upgrade (Alpine)
      tags: always
      apk:
        update_cache: yes
        upgrade: yes

  when: ansible_distribution == "Alpine"

- name: upgrade (Rocky)
  tags: always
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "Rocky"

- name: install the basic packages
  tags: always
  package:
    name: [htop,neofetch,tree,zsh,ranger,unzip,git,"{{ vim }}",speedtest-cli,wget,curl,tmux,rsync,"{{ locate }}","{{ numlockx }}"]
    state: latest

- name: install more basic packages for Alpine
  tags: always
  apk:
    name: [lsof,less,lsblk,util-linux]
    state: latest
  when: ansible_distribution == "Alpine"

- name: add a cron job for updatedb (locate)  every 10min
  tags: always
  cron:
    name: "Update database for locate"
    minute: "*/5"
    job: "updatedb"

