- name: make Alpine accept sudo users
  block:

    - name: install sudo, bash packages
      tags: firstrun,alpine
      apk:
        name: [sudo,bash]
        state: latest      

    - name: remove comment in the /etc/sudoers file
      tags: firstrun,alpine
      lineinfile:
        path: /etc/sudoers
        regex: '# %sudo'
        line: '%sudo   ALL=(ALL:ALL) ALL'
        owner: root
        group: root
        mode: 0440

  when: ansible_distribution == "Alpine"

- name: create sudo/wheel groups
  tags: firstrun
  group:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - wheel

- name: create eddie user
  tags: firstrun
  user:
    name: "{{ item.name }}"
    password: "{{ item.passwd }}"
    update_password: on_create
    create_home: yes
    groups: "{{ item.groups }}"
    append: yes
    shell: /bin/bash
  register: user
  loop: "{{ users }}"


- name: copy sudoer_eddie file to /etc/sudoers.d/eddie
  tags: firstrun,singleuser
  copy:
    src: sudoer_eddie
    dest: /etc/sudoers.d/eddie
    owner: root
    group: root
    mode: 0440
  when: user.changed

- name: copy SSH key eddie user
  tags: firstrun
  authorized_key:
    user: eddie
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHwLqywqLhqZ5Nj03X6LYppdAUofFDCv8mNS+cOns/E7 eddie main key      

- name: set PAM in Ansible (ansible user can ssh Alpine)
  block:

    - name: install openssh-server-pam package
      apk:
        name: openssh-server-pam
        state: latest

    - name: edit sshd_config file to allow PAM
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '# UsePAM'
        line: 'UsePAM yes'
        owner: root
        group: root
        mode: 0644
      register: pam

    - name: restart sshd service
      service:
        name: sshd
        state: restarted
      when: pam.changed

  when: ansible_distribution == "Alpine"

- name: create ansible user
  tags: firstrun
  user:
    name: ansible
    groups: root,sudo
    shell: /bin/bash

- name: copy sudoer_ansible file to /etc/sudoers.d/ansible
  tags: firstrun
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy the SSH key ansible user
  tags: firstrun
  authorized_key:
    user: ansible
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOWBKMr4lAZEzKiqXslcqDgmId5MCgQw3Pf2tNRWeNee ansible key

