- name: check if nextcloud post install can be started - condition 01
  tags: nextcloud_post_install
  stat:
    path: /root/.nextcloud.txt
  register: nextcloud

- name: check if nextcloud post install can be started - condition 02
  tags: nextcloud_post_install
  stat:
    path: /root/.nextcloud_post_install.txt
  register: nextcloud_post_install

- name: edit config.php file block
  tags: nextcloud_post_install
  block:

    - name: insert nextcloud domain as trusted domains array
      lineinfile:
        path: /var/www/nextcloud/config/config.php
        insertafter: '0 =>'
        line: "    1 => 'nextcloud.eddienetworks.ddnsfree.com',"

    - name: replace overwrite.cli.urlfield
      lineinfile:
        path: /var/www/nextcloud/config/config.php
        regexp: 'overwrite.cli.url'
        line: "  'overwrite.cli.url' => 'https://nextcloud.eddienetworks.ddnsfree.com',"

    - name: add overwriteprotocol field
      lineinfile:
        path: /var/www/nextcloud/config/config.php
        insertafter: 'overwrite.cli.url'
        line: "  'overwriteprotocol' => 'https',"

    - name: add remaning of the configuration
      blockinfile:
        dest: /var/www/nextcloud/config/config.php
        block: "{{ lookup('file', 'config.txt') }}"
        insertafter: "installed"
        backup: yes
        marker: "// {mark} ANSIBLE MANAGED BLOCK \\ "

    - name: add user www-data to redis group
      tags: nextcloud_post_install
      user:
        name: www-data 
        groups: redis
        append: yes
      register: redis

    - name: restart apache webserver
      tags: nextcloud_post_install
      service:
        name: apache2
        state: restarted
      when: redis.changed

    - name: create /mnt/nextcloud folder to mount usb stick
      tags: nextcloud_post_install
      file:
        path: /mnt/nextcloud 
        state: directory
        owner: eddie
        group: www-data
        mode: 0770

    - name: mount usb stick and create /etc/fstab mount point
      tags: nextcloud_post_install
      mount:
        src: UUID=eb090bfd-603a-44c3-a503-87536aa53e74
        path: /mnt/nextcloud
        fstype: auto
        state: mounted

    - name: create folders to create a mount bind
      tags: nextcloud_post_install
      file:
        path: "{{ item }}"
        state: directory
        owner: eddie
        group: www-data
        mode: 0770
      loop:
        - /mnt/nextcloud/eddie/files
        - /var/www/nextcloud/data/eddie/files

    - name: mount bind the folders created
      tags: nextcloud_post_install
      mount:
        src: /mnt/nextcloud/eddie/files
        path: /var/www/nextcloud/data/eddie/files 
        fstype: none
        state: mounted
        opts: bind

    - name: add cron job for cron.php
      tags: nextcloud_post_install
      cron:
        name: " {{ item.name }}"
        minute: "*/10"
        hour: "*"
        job: "{{ item.job }}"
      loop:
        - { name: "cron.php", job: "sudo -u www-data php -f /var/www/nextcloud/cron.php" } 
        - { name: "file scan", job: "sudo -u www-data php /var/www/nextcloud/occ files:scan --all" }
   
    - name: create the file /root/.nextcloud_post_install.txt
      file:
        path: /root/.nextcloud_post_install.txt
        state: touch
        owner: root
        group: eddie
        mode: 0770

  when: 
    - nextcloud.stat.exists
    - not nextcloud_post_install.stat.exists
