- name: copy tmux configuration file
  tags: always
  copy:
    src: tmux.conf
    dest: "/home/{{ item.name }}/.tmux.conf"
    owner: "{{ item.name }}"
    mode: 0664
  loop: "{{ users }}"

- name: create a ".config/ranger" folder
  file:
    state: directory
    path: "/home/{{ item.name }}/.config/ranger"
    owner: "{{ item.name }}"
    mode: 0644
  loop: "{{ users }}"

- name: copy ranger configuration file
  tags: ranger
  copy:
    src: rc.conf
    dest: "/home/{{ item.name }}/.config/ranger/rc.conf"
    owner: "{{ item.name }}"
    mode: 0664
  loop: "{{ users }}"
