- name: install ddclient
  tags: ddclient
  apt:
    name: ddclient
    state: latest

- name: copy ddclient config file
  tags: ddclient
  copy:
    src: ddclient
    dest: /etc/ddclient.conf
    owner: root
    group: root
    mode: 0600
  register: ddclient_config

- name: restart ddclient
  tags: ddclient
  service:
    name: ddclient
    state: restarted
  when: ddclient_config.changed
