
- name: clone reverse-proxy git repository
  tags: reverse_proxy
  git:
    repo: https://github.com/ebiscaia/reverse_proxy.git
    dest: /root/reverse_proxy
    force: yes

- name: copy repo to eddie folder
  tags: reverse_proxy
  copy:
    remote_src: true
    src: /root/reverse_proxy
    dest: /home/eddie/
    owner: eddie
    group: eddie
    mode: 0770
    
- name: mount bind folder with /etc/nginx/http.d
  tags: reverse_proxy
  mount:
    path: /etc/nginx/http.d
    src: /home/eddie/reverse_proxy
    opts: bind
    state: mounted
    fstype: none

- name: install certbot-nginx package
  tags: reverse_proxy
  package:
    name: certbot-nginx
    state: latest

- name: copy the letsencrypt zip file
  tags: reverse_proxy
  unarchive:
    src: letsencrypt.zip
    dest: /etc/
    owner: root
    group: root

- name: create symlinks for the keys
  file:
    src: "/etc/letsencrypt/archive/{{ item.0 }}/{{ item.1 }}1.pem"
    dest: "/etc/letsencrypt/live/{{ item.0 }}/{{ item.1 }}.pem"
    state: link
    owner: root
    group: root
    mode: 0777
  loop: "{{ ['anotherlinuxuser.ddnsfree.com', 'anotherlinuxuser.ddnsfree.com-0001', 'eddienetworks.ddnsfree.com', 'eddienetworks.ddnsfree.com-0001']|product(['cert','privkey','fullchain','chain'])|list }}"

- name: create and install certificate using certbot --nginx plugin
  tags: reverse_proxy
  command: "certbot --nginx -d {{ item }} -m ebiscaia@me.com --agree-tos --noninteractive --redirect"
  loop:
    - anotherlinuxuser.ddnsfree.com
    - eddienetworks.ddnsfree.com
  register: certificate

- name: copy dynu credentials to run certbot-dns-dynu plugin to upgrade the certicate
  tags: reverse_proxy_update
  copy:
    src: dynu-credentials.ini
    dest: /home/eddie/.dynu-credentials.ini
    owner: eddie
    group: eddie
    mode: 0640

- name: install python3-pip package (necessary to install certbot-dns-dynu plugin)
  tags: reverse_proxy_update
  package:
    name: "{{ pip }}"
    state: latest

- name: install certbot-dns-dynu plugin using python3-pip
  tags: reverse_proxy_update
  pip:
    name: certbot-dns-dynu
    state: present

- name: restart nginx
  tags: reverse_proxy_update
  service:
    name: nginx
    state: restarted
  when: certificate.changed

- name: create a cron job to renew the certificates automatically
  tags: reverse_proxy
  cron:
    name: "{{ item.name }}"
    minute: "22"
    hour: "{{ item.hour }}"
    weekday: "{{ item.weekday }}"
    job: "{{ item.command }}"
  loop:
    - { name: "renew certificates", command: "certbot renew --authenticator dns-dynu --dns-dynu-credentials /home/eddie/.dynu-credentials.ini --dns-dynu-propagation-seconds 240", weekday: "*", hour: "1" }
    - { name: "remove old certificates", command: "rm -r /var/log/letsencrypt/*", weekday: "0", hour: "0" }
