- name: pre-install tasks for Rocky
  block:
          
    - name: disable SELinux
      tags: pihole
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=disabled
      register: selinux

    - name: install binding for firewalld and python
      tags: pihole
      dnf:
        name: python3-firewall
        state: present

    - name: enable traffic for http, https
      tags: pihole
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - http
        - https

    - name: reboot system to apply changes
      tags: pihole
      reboot:
      when: selinux.changed

  when: ansible_distribution == "Rocky"

- name: check if pihole was installed
  stat:
    path: /etc/.pihole
  register: pihole

- name: pihole general pre-install
  block:

    - name: show a message asking to run the script manually on the hosts
      debug:
        msg: 
          - "Pihole pre-install is finished. Please refresh your package manager and run the following script before running Ansible again"
          - "curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash"
      failed_when: result.rc == 0

  when: not pihole.stat.exists          
