- name: pre-install tasks for Rocky
  block:
          
    - name: disable SELinux
      tags: pihole
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=disabled
      register: selinux

    - name: install binding for firewalld and python
      tags: pihole
      dnf:
        name: python3-firewall
        state: latest

    - name: enable traffic for necessary services on firewalld
      tags: pihole
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - http
        - https
        - dns
        - dhcp
        - dhcpv6

    - name: create FTL firewall zone
      tags: pihole
      ansible.posix.firewalld:
        zone: ftl
        state: present
        permanent: yes
    - name: add network interface to FTL firewall zone
      tags: pihole
      ansible.posix.firewalld:
        zone: ftl
        interface: lo
        permanent: yes
        state: enabled

    - name: add port 4711/tcp to FTL firewall zone
      tags: pihole
      ansible.posix.firewalld:
        zone: ftl
        port: 4711/tcp
        permanent: yes
        state: enabled
        
    - name: reboot system to apply changes
      tags: pihole
      reboot:
      when: selinux.changed

  when: ansible_distribution == "Rocky"

- name: install sqlite3 to allow adding lists to gravity.db on CLI
  package:
    name: "{{ sqlite }}"
    state: latest

- name: check if pihole was installed
  stat:
    path: /etc/.pihole
  register: pihole

- name: pihole general pre-install
  block:

    - name: show a message asking to run the script manually on the hosts
      debug:
        msg: 
          - "Pihole pre-install is finished. Please refresh your package manager and run the following script before running Ansible again"
          - "curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash"
      failed_when: result.rc == 0

  when: not pihole.stat.exists          
